### ISSUE TITLE
Not working in my project

### ISSUE THREAD

**Issue by WebGenerator** [benmajor/RedSeed#1]
Plugin 'seed' does not exist, add this plugin using: R::ext('seed'). Have issues

**Comment by benmajor** [comment]
How have you installed the project? Did you use Composer? Please share some code.

**Comment by WebGenerator** [comment]
Yes, composer, project is working example of code below
	$users = \R::seed('users', 10, [
   'email' => 'email()',
   'login' => 'word(3,10)',
  'password' => 'word(5,15)',
  'status' =>  'integer(1,2)'
 
		]);

**Comment by benmajor** [comment]
Please post your `composer.json` file, as well as your full code (I can't see anywhere you're referencing `require 'vendor/autoload.php`.

**Comment by WebGenerator** [comment]
{
    "name": "top/top",
    "require": {
        "vlucas/valitron": "^1.4",
        "intervention/image": "^2.5",
        "benmajor/redseed": "^1.0"
    },
	"autoload":{
	"psr-4":{
	"top\\": "vendor/top",
	"app\\": "app"
	}
	}
}

**Comment by WebGenerator** [comment]
the project works, it's a catalog, i'm installing your package for testing seed, but i see this message "Plugin 'seed' does not exist, add this plugin using: R::ext('seed')", redbean works

**Comment by benmajor** [comment]
This seems to be an autoloading issue in Composer. Calling `class_exists('BenMajor\\RedSeed\\RedSeed');` before running `R::seed()` resolves the issue, for some reason.

I need to look into it further, but the following works as expected:

```php
<?php

require 'vendor/autoload.php';

use RedBeanPHP\R;

class_exists('BenMajor\\RedSeed\\RedSeed');

R::setup(
    'mysql:dbname=redseed;host=localhost',
    'root',
    'root'
);

R::seed('user', 10, [
    'forename' => 'word(3,10)',
    'surname' => 'word(5,15)',
    'email' => 'email()'
]);
```

**Comment by WebGenerator** [comment]
the project works, it's a catalog, i'm installing your package for testing seed, but i see this message "Plugin 'seed' does not exist, add this plugin using: R::ext('seed')", redbean works

**Comment by WebGenerator** [comment]
Yes, thanks - it's that i need
	public function seeding(){
		class_exists('BenMajor\\RedSeed\\RedSeed');
		$users = \R::seed('users', 10, [
   'email' => 'email()',
   'login' => 'word(3,10)',
  'password' => 'word(5,15)',
  'status' =>  'integer(1,2)'
 
		]);
		
	}

**Comment by KoljaL** [comment]
I had the same error, but your solution works for me too :-)
